### ISSUE TITLE
Tibet最新版

### ISSUE THREAD

**Issue by handsomehu** [adoggie/Tibet.6#1]
hi Scott, 
请问0.6版是最新的吗？ 看到还有个五个月前的版本,是不是老版本？
Best regards,
Leon

**Comment by adoggie** [comment]
是的，还在不断改进中，增加ui管理，监控



---原始邮件---
发件人: "Leon Zhao"<notifications@github.com&gt;
发送时间: 2019年11月7日(星期四) 中午12:54
收件人: "adoggie/Tibet.6"<Tibet.6@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [adoggie/Tibet.6] Tibet最新版 (#1)



hi Scott,
 请问0.6版是最新的吗？ 看到还有个五个月前的版本,是不是老版本？
 Best regards,
 Leon

**Comment by handsomehu** [comment]
期待！

**Comment by adoggie** [comment]
等着我，快的！！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Leon Zhao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 下午2:42
收件人:&nbsp;"adoggie/Tibet.6"<Tibet.6@noreply.github.com&gt;;
抄送:&nbsp;"橄榄条"<24509826@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [adoggie/Tibet.6] Tibet最新版 (#1)




期待！
